 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build EvilFizzBuzz\EvilFizzBuzz.sln
       - run: dotnet test EvilFizzBuzz\EvilFizzBuzz.sln
       - run: dotnet publish EvilFizzBuzz\EvilFizzBuzz.sln
       - store_artifacts:
          path: C:\Users\circleci\project\EvilFizzBuzz\EvilFizzBuzz\bin\Debug\netcoreapp2.1\publish\
